name: docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install GDAL dependencies
      run: |
        sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev python3-gdal

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build your project
      run: |
        python setup.py install