name: docs
on:
    push:
        branches:
            - main
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install codespell
              run: |
                    python -m pip install --upgrade pip
                    pip install codespell

            - name: Run codespell
              run: codespell

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install folium
                  pip install geopandas
                  pip install ipyleaflet
                  pip install mkdocs
                  pip install mkdocs-material
                  pip install mkdocstrings  # Add this line to install mkdocstrings plugin
                  pip install mkdocs-git-revision-date-localized-plugin

            - name: Verify plugin installation
              run: |
                  pip show mkdocs-git-revision-date-localized-plugin

            - name: Build documentation
              run: mkdocs build --clean


            - name: Discover typos with codespell
              run: |
                  codespell --skip="*.csv,*.geojson,*.json,*.js,*.html,*cff,./.git" --ignore-words-list="aci,hist"
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/

            - name: Install MkDocs
              run: |
                  pip install mkdocs mkdocs-material

            - run: mkdocs gh-deploy --force
