on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

name: Linux installation
jobs:
    test-ubuntu:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Cache Python dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt -r requirements_dev.txt

            - name: Validate dependencies
              run: python -m pip check

            - name: Install package
              run: pip install .

            - name: Test import
              run: python -c "import geopop; print('geopop import successful')"

            - name: Test functionality
              run: python -c "from geopop import Map; print('Map class loaded successfully')"

            - name: Run unit tests
              run: python -m unittest discover tests/