name: pypi

on:
    release:
        types: [created]

jobs:
    deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Verify PyPI credentials
              run: |
                  if [ -z "${{ secrets.PYPI_USERNAME }}" ] || [ -z "${{ secrets.PYPI_PASSWORD }}" ]; then
                      echo "PyPI credentials are not set!"
                      exit 1
                  fi

            - name: Clean previous builds
              run: |
                  rm -rf dist/

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install setuptools wheel twine build

            - name: Test the build
              run: |
                  python -m build
                  twine check dist/*

            - name: Test package installation
              run: |
                  pip install dist/*.whl
                  python -c "import geopop; print('geopop import successful')"

            - name: Build and publish
              env:
                  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
                  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
              run: |
                  python -m build
                  twine upload --skip-existing dist/*